name: puppet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-155.0.dev <4.0.0'

dependencies:
  app_dirs: ^0.2.0
  args: ^2.4.2
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  hotkey_manager: ^0.1.8
  screen_retriever: ^0.1.9
  smooth_page_indicator: ^1.1.0
  system_fonts: ^1.0.1
  tray_manager: ^0.2.1
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/logo.png
    - assets/logo_64.png
    - assets/logo_32.ico
    - assets/icon_wheel.png
    - assets/icon_list.png
    - assets/transparent_bg.png
