name: puppet
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-155.0.dev <4.0.0"

dependencies:
  args: ^2.4.2
  auto_size_text: ^3.0.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_iconpicker: ^4.0.1
  flutter_markdown: ^0.7.6+2
  flutter_riverpod: ^2.4.9
  flutter_rust_bridge: 2.9.0
  font_awesome_flutter: ^10.6.0
  gradient_borders: ^1.0.1
  hotkey_manager: ^0.2.3
  http: ^1.3.0
  rust_lib_puppet:
    path: rust_builder
  screen_retriever: ^0.2.0
  smooth_page_indicator: ^1.1.0
  system_fonts: ^1.0.1
  tray_manager: ^0.2.1
  url_launcher: ^6.3.1
  wayland_layer_shell: ^1.0.1
  window_manager: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.7
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/config_macos.json
    - assets/config_linux.json
    - assets/config_windows.json
    - assets/logo.png
    - assets/logo_64.png
    - assets/logo_32.ico
    - assets/icon_wheel.png
    - assets/icon_list.png
    - assets/transparent_bg.png
