icon: assets/logo.png
summary: dynamic menu
group: Application/Utilities
vendor: metin ur
packager: metin ur
packagerEmail: metinur.1311@gmail.com
license: MIT
url: https://github.com/Mr-1311/puppet

display_name: puppet

keywords:
  - dynamic menu
  - application launcher

generic_name: puppet

categories:
  - Utility

startup_notify: true
# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml